version: "2"
run:
  modules-download-mode: readonly

linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - depguard
    - durationcheck
    - errcheck
    - errchkjson
    - exhaustive
    - funlen
    - gocheckcompilerdirectives
    - gochecksumtype
    - gocognit
    - gocyclo
    - gomoddirectives
    - gosec
    - gosmopolitan
    - govet
    - ineffassign
    - loggercheck
    - maintidx
    - makezero
    - musttag
    - nestif
    - nilerr
    - nilnesserr
    - noctx
    - perfsprint
    - prealloc
    - reassign
    - recvcheck
    - spancheck
    - sqlclosecheck
    - staticcheck
    - unparam
    - unused
    - zerologlint
  settings:
    depguard:
      rules:
        main:
          list-mode: lax
          deny:
            - pkg: "math/rand$"
              desc: use math/rand/v2
            - pkg: "github.com/sirupsen/logrus"
              desc: not allowed
            - pkg: "github.com/pkg/errors"
              desc: Should be replaced by standard lib errors package
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
