version: "3"

tasks:
  go:build:
    desc: "Build the go binary"
    cmd: go build -o bin/main ./cmd/...
  go:run:
    desc: "Run the go binary"
    deps:
      - go:build
    cmd: ./bin/main
  go:test:
    desc: "Run down-pvscope tests"
    cmd: go test -v ./...
  linux:build:
    desc: "Build the go binary for an linux container"
    cmd: CGO_ENABLED=0 GOARCH=amd64 GOOS=linux go build -o bin/main ./cmd/...
  docker:build:
    deps:
      - linux:build
    cmds:
      - docker buildx build . -t docker.shifman.dev/shifman/down-pvscope --platform linux/arm64,linux/amd64
      - docker push docker.shifman.dev/shifman/down-pvscope
  proto:gen:
    desc: "Generate protobuf"
    cmd: buf generate
