apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-worker
  labels:
    {{- $ctx := deepCopy . -}}
    {{- $_ := set $ctx.Values "component" "worker" -}}
    {{- include "commonLabels" $ctx | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- $ctx := deepCopy . -}}
      {{- $_ := set $ctx.Values "component" "worker" -}}
      {{- include "selectorLabels" $ctx | nindent 6 }}
  replicas: 1
  template:
    metadata:
      labels:
        {{- $ctx := deepCopy . -}}
        {{- $_ := set $ctx.Values "component" "worker" -}}
        {{- include "commonLabels" $ctx | nindent 8 }}
        {{- with .Values.extraPodLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{.Release.Name}}-sa
      securityContext:
        fsGroupChangePolicy: "OnRootMismatch"
        runAsNonRoot: true
        fsGroup: 2000
        runAsUser: 1000
        runAsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      automountServiceAccountToken: true
      containers:
        - securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
          command:
            - ./main
          args:
            - --temporal-url=temporal-frontend.temporal.svc.cluster.local.:7233
            - --temporal-namespace=down-pvscope
          imagePullPolicy: {{.Values.imagePullPolicy}}
          name: worker
          image: {{.Values.image}}:{{.Values.version | default "latest"}}
