apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pv-editor-role
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["update", "list", "get", "delete"]
