# https://kubernetes.io/docs/concepts/storage/persistent-volumes/
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bogus
  namespace: down-pvscope
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
